### ISSUE TITLE
Build failed: uniffi-bindgen: command not found

### ISSUE THREAD

**Issue by danielnordh** [bitcoindevkit/bdk-swift#15]
When attempting to update the bdk-ffi version I followed the guide but after executing
`./build.sh  `

I got the following error
```
Confirm bdk-ffi rust lib builds
Finished release [optimized] target(s) in 0.73s
Generate bdk-ffi swift bindings
./build.sh: line 10: uniffi-bindgen: command not found
```

I'm guessing it's due to uniffi-bindgen not being added to my paths, but never having used rust/cargo before I have no idea where it might be located.

**Comment by notmandatory** [comment]
Sorry docs are out of date, once we update to upcoming `bdk-ffi` `0.6.0` you won't have to do this, but right now for `bdk-swift` you need to manually install `uniffi-bindgen` with this command before building:
```shell
cargo install uniffi_bindgen --version 0.16.0
```
