### ISSUE TITLE
Reduce the size of libbdkffi.a files for apple targets

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk-swift#25]
See [discussion on discord](https://discord.com/channels/753336465005608961/824249944810192956/996479807154032660) and [min-sized-rust](https://github.com/johnthagen/min-sized-rust).

For swift we currently make binary libs for 5 target platforms (size today):
x86_64-apple-darwin (66M)
aarch64-apple-darwin (64M)
x86_64-apple-ios (73M)
aarch64-apple-ios (166M)
aarch64-apple-ios-sim (159M) 

See also @thunderbiscuit [Library Sizes](https://hackmd.io/@thunderbiscuit/languagebindingsnotesfordevs/%2FzqsHeL4KSeaEWd9vomeRWg)

**Comment by notmandatory** [comment]
Related links:

[Stackoverflow suggested changes](https://stackoverflow.com/questions/29008127/why-are-rust-executables-so-huge/54842093#54842093)

We will need to wait for rustc 1.63 to fix strip error for .dylib files, but we're using .a files so it isn't needed except to clean up log messages, see [rust-lang #97991](https://github.com/rust-lang/rust/pull/97991).

**Comment by quad** [comment]
Won't stripping symbols make tracebacks useless? I'd assume that any downstream _application_ can decide on whether to strip the symbols?

Is the worry about the total size of the library (e.g. time to download in toolchains) or the size of the library in the final application (e.g. time to download for final applications)?

**Comment by thunderbiscuit** [comment]
Our main concern is size of the library once it's shipped in an application. I currently don't know enough about iOS to properly evaluate that. @quad is that something you would know how to get? That would at least give us a benchmark. At the moment I simply logged the download size for the whole package and it's components, but I don't really know how those translate into a app you'd deploy on the App Store.
